### ISSUE TITLE
HU-4

### ISSUE THREAD

**Issue by aringapoki** [Caarolinaa/DEV002-social-network#14]
yo como activista vegano
quiero escribir, publicar un post
para difundir información útil para la comunidad

**Comment by aringapoki** [comment]
**Criterios de aceptación**

**Comment by Caarolinaa** [comment]
`Definición de Terminado`

- [ ] Es una SPA
- [ ]  Utiliza un router para cambiar contenido dinámicamente desde JS
- [ ]  Haber recibido code review de al menos una compañera
- [ ]  Pasó por pruebas de usabilidad
- [ ]  Fue desplegada en github pages (para asegurar que funciona router)
- [ ]  Uso de html semántico
- [ ] Pasan los Test Unitarios
- [ ] Resolver errores e imperfecciones que nos devuelven los test
